### PR TITLE
feat(metrics-type): Add metrics type

### PR DESCRIPTION
**Pull request by pavelsidla**

### CODE REVIEW

**Comment by fotosidla** [comment]
Hello this PR adds changes from previous PR (https://github.com/electrolux-oss/aws-cost-exporter/pull/14) from ylascauxoc
And also add ability to define one of AmortizedCost, BlendedCost, NetAmortizedCost, NetUnblendedCost, NormalizedUsageAmount, UnblendedCost, and UsageQuantity metrics type.

**Comment by gluckzhang** [comment]
Hi @fotosidla, thanks for this PR. Looks interesting! I will check both yours and #14 today and get back to you soon :)

**Comment by gluckzhang** [comment]
Hi @pavelsidla, #14 has been reviewed and merged. Could you please rebase the main branch to fix the conflicts? Thank you!

**Comment by pavelsidla** [comment]
Hello it should be done now

**Comment by pavelsidla** [comment]
Hi is it ok?

**Review by gluckzhang — COMMENTED** [review]
Hi @pavelsidla , thanks for fixing the conflicts. The code looks pretty good and I am merging this PR. It is a quite useful feature :)

**Review by gluckzhang — APPROVED** [review]

**Pull request merged**
